database = [
    {
        "id": 10,
        "judul": "ide konten promosi hampers lebaran",
        "category": "tips",
        "like": 2200,
        "posting_ulang": 400,
        "share": 1200,
        "hashtags": "#yorscakery #fyp #idekonten #kontenpromosi #fyprells",
        "caption": "silau banget ni hampers yors untuk lebaran tahun ini!! 😎🩷",
    },
    {
        "id": 8,
        "judul": "ide caption buat post foto bareng teman!",
        "category": "lifestyle",
        "like": 1331,
        "posting_ulang": 76,
        "share": 1847,
        "hashtags": "#explorepage #exploremore #tips #besties",
        "caption": "kalian tim caption panjang atau pendek? 🤭\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 9,
        "judul": "ide caption aesthetic bahasa latin",
        "category": "lifestyle",
        "like": 4875,
        "posting_ulang": 377,
        "share": 1847,
        "hashtags": "#explorepage #exploremore #tips #besties",
        "caption": "aesthetic banget buat feed kamu! 🤍✨\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 1,
        "judul": "Beberapa website Photobooth buat kamu",
        "category": "lifestyle",
        "like": 2287,
        "posting_ulang": 118,
        "share": 3043,
        "hashtags": "#explorepage #exploremore #tips #poseideas #pose",
        "caption": "hope it helps!! 🩷\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 6,
        "judul": "secret code dan artinya buat ngodein crush kamu!",
        "category": "tips",
        "like": 5417,
        "posting_ulang": 387,
        "share": 3793,
        "hashtags": "#explorepage #exploremore #tips #birthdaygirl",
        "caption": "kamu kirim angka ini ke dia, berani nggaaa? 👀\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 3,
        "judul": "Rekomendasi lagu buat kode doi",
        "category": "tips",
        "like": 4164,
        "posting_ulang": 220,
        "share": 4147,
        "hashtags": "#exploremore #explorepage #song #songs #songlyrics",
        "caption": "ada lagu favorit kaliann?\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 5,
        "judul": "ide ucapan selain 'terimakasih' kalo lagi dipuji orang!",
        "category": "productivity",
        "like": 5283,
        "posting_ulang": 200,
        "share": 6119,
        "hashtags": "#explorepage #exploremore #tips",
        "caption": "save ini biar ngga kelupaan 🫶🏻🫶🏻\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 44,
        "judul": "perbedaan S1, S2, dan S3 yang harus kamu pahami!",
        "category": "education",
        "like": 7800,
        "posting_ulang": 460,
        "share": 6500,
        "hashtags": "#college #education #mahasiswa #tips #explorepage",
        "caption": "mau lanjut studi tapi masih bingung bedanya? ini penjelasannya! 🎓📖\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 28,
        "judul": "kenapa kamu harus minum air putih sebelum sarapan?",
        "category": "health",
        "like": 8700,
        "posting_ulang": 430,
        "share": 7200,
        "hashtags": "#health #hydration #morninghabits #tipssehat #explorepage",
        "caption": "kebiasaan kecil yang dampaknya besar banget! 💧☀️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 17,
        "judul": "kombinasi warna outfit yang selalu kelihatan modis",
        "category": "fashion",
        "like": 8760,
        "posting_ulang": 510,
        "share": 7430,
        "hashtags": "#fashion #colorpairing #ootd #styleinspo #explorepage",
        "caption": "simpan buat referensi belanja berikutnya! 🎨👚\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 54,
        "judul": "cara baca laporan keuangan buat pemula (anti ribet)!",
        "category": "finance",
        "like": 8900,
        "posting_ulang": 510,
        "share": 7600,
        "hashtags": "#finance #saham #laporankeuangan #investasi #fyp",
        "caption": "mau beli saham tapi bingung baca laporannya? ini panduannya! 📄🔍\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 143,
        "judul": "cara menulis catatan rapat yang efektif dan ringkas!",
        "category": "productivity",
        "like": 9400,
        "posting_ulang": 550,
        "share": 7900,
        "hashtags": "#productivity #meetingnotes #notetaking #tips #explorepage",
        "caption": "rapat 1 jam bisa diringkas jadi 1 halaman, ini caranya! 📋✍️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 40,
        "judul": "cara menulis email ke dosen yang sopan dan profesional!",
        "category": "education",
        "like": 9300,
        "posting_ulang": 580,
        "share": 8100,
        "hashtags": "#college #tips #email #mahasiswa #explorepage",
        "caption": "jangan sampai salah format, dosen bisa langsung skip lho! 📧🎓\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 62,
        "judul": "tips packing koper buat liburan singkat 3 hari!",
        "category": "lifestyle",
        "like": 9800,
        "posting_ulang": 590,
        "share": 8300,
        "hashtags": "#lifestyle #travel #packing #tips #explorepage",
        "caption": "anti bawaan meledak, ini triknya! 🧳✈️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 139,
        "judul": "cara buat sistem inbox zero di email kamu!",
        "category": "productivity",
        "like": 11200,
        "posting_ulang": 650,
        "share": 9600,
        "hashtags": "#productivity #email #inboxzero #tips #explorepage",
        "caption": "1000+ email belum dibaca? kita beresin bareng! 📧✅\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 14,
        "judul": "template to-do list harian biar hidup lebih teratur",
        "category": "productivity",
        "like": 13600,
        "posting_ulang": 870,
        "share": 9800,
        "hashtags": "#productivity #todolist #planner #selfimprovement #fyp",
        "caption": "yang sering lupa agenda, ini buat kalian! 📋🗓️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 30,
        "judul": "postur duduk yang benar biar pinggang ngga cepat pegal!",
        "category": "health",
        "like": 11400,
        "posting_ulang": 670,
        "share": 9900,
        "hashtags": "#health #posture #workfromhome #tipssehat #explorepage",
        "caption": "yang seharian duduk di depan laptop, ini buat kalian! 🪑💻\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 112,
        "judul": "cara backup data HP secara otomatis tanpa ribet!",
        "category": "technology",
        "like": 11600,
        "posting_ulang": 680,
        "share": 9900,
        "hashtags": "#technology #backup #smartphone #tips #fyp",
        "caption": "jangan nunggu HP hilang baru nyesel! 📱💾\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 21,
        "judul": "cara merespons kritik dengan elegan tanpa drama",
        "category": "productivity",
        "like": 11800,
        "posting_ulang": 730,
        "share": 10400,
        "hashtags": "#selfgrowth #tips #mindset #mentalhealth #explorepage",
        "caption": "skill ini penting banget buat kehidupan sehari-hari! 🌱🤝\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 37,
        "judul": "manfaat ikut organisasi kampus yang jarang dibahas!",
        "category": "education",
        "like": 12600,
        "posting_ulang": 740,
        "share": 10800,
        "hashtags": "#college #organisasi #mahasiswa #selfgrowth #fyp",
        "caption": "bukan cuma buat CV, ada banyak hal lain yang kamu dapet! 🏛️🤝\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 78,
        "judul": "cara jaga hubungan pertemanan jarak jauh!",
        "category": "relationship",
        "like": 12400,
        "posting_ulang": 720,
        "share": 10800,
        "hashtags": "#relationship #friendship #LDR #besties #fyp",
        "caption": "teman sejati tetap deket walau udah beda kota! 🤝❤️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 129,
        "judul": "cara riset yang efektif menggunakan Google Scholar!",
        "category": "education",
        "like": 12900,
        "posting_ulang": 740,
        "share": 11100,
        "hashtags": "#education #research #googlescholar #tips #explorepage",
        "caption": "cari jurnal ilmiah ngga harus bingung, ini caranya! 🔬📄\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 13,
        "judul": "cara belajar efektif pakai metode Pomodoro!",
        "category": "education",
        "like": 9450,
        "posting_ulang": 620,
        "share": 11200,
        "hashtags": "#education #studytips #pomodoro #belajar #explorepage",
        "caption": "cobain deh, dijamin fokusnya nambah! ⏱️📚\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 124,
        "judul": "cara pilih sepatu yang nyaman dan tetap fashionable!",
        "category": "fashion",
        "like": 13100,
        "posting_ulang": 760,
        "share": 11400,
        "hashtags": "#fashion #shoes #footwear #styleips #fyp",
        "caption": "kaki happy, penampilan makin percaya diri! 👟🛍️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 171,
        "judul": "tips hemat listrik di rumah tanpa ngurangin kenyamanan!",
        "category": "finance",
        "like": 14100,
        "posting_ulang": 820,
        "share": 12000,
        "hashtags": "#finance #hematatrik #saving #rumah #explorepage",
        "caption": "tagihan listrik bisa turun 30% dengan trik ini! ⚡🏠\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 53,
        "judul": "beda tabungan biasa vs deposito, mana yang lebih cuan?",
        "category": "finance",
        "like": 14200,
        "posting_ulang": 830,
        "share": 12400,
        "hashtags": "#finance #deposito #tabungan #literasikeuangan #explorepage",
        "caption": "uangmu diam di rekening? mending kerja sekalian! 🏦📈\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 138,
        "judul": "metode GTD (Getting Things Done) untuk pemula!",
        "category": "productivity",
        "like": 14700,
        "posting_ulang": 860,
        "share": 12400,
        "hashtags": "#productivity #GTD #timemanagement #organized #fyp",
        "caption": "kepala penuh pikiran? ini cara kosongkan dan tetap produktif! 🧹💡\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 119,
        "judul": "cara rawat pakaian biar tahan lama dan tetap bagus!",
        "category": "fashion",
        "like": 14300,
        "posting_ulang": 840,
        "share": 12700,
        "hashtags": "#fashion #clothingcare #tips #laundry #explorepage",
        "caption": "baju favorit kamu bisa awet bertahun-tahun kalau tau caranya! 👕🧺\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 60,
        "judul": "ide aktivitas seru saat hujan di rumah!",
        "category": "lifestyle",
        "like": 14600,
        "posting_ulang": 870,
        "share": 12900,
        "hashtags": "#lifestyle #stayhome #rainydays #activity #explorepage",
        "caption": "hujan = healing time kalau tau caranya! 🌧️🕯️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 102,
        "judul": "tips aman belanja online biar ngga kena tipu!",
        "category": "tips",
        "like": 14900,
        "posting_ulang": 870,
        "share": 13000,
        "hashtags": "#tips #belanja #onlineshopping #aman #explorepage",
        "caption": "jangan sampai nyesel setelah transfer! cek ini dulu 🛒⚠️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 25,
        "judul": "tanda-tanda tubuh kamu kekurangan vitamin D!",
        "category": "health",
        "like": 14800,
        "posting_ulang": 890,
        "share": 13100,
        "hashtags": "#health #vitaminD #tipssehat #awareness #fyp",
        "caption": "cek dulu, jangan sampai diabaikan ya! ☀️🩺\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 134,
        "judul": "rekomendasi podcast bahasa Indonesia buat nambah ilmu!",
        "category": "education",
        "like": 15300,
        "posting_ulang": 900,
        "share": 13100,
        "hashtags": "#education #podcast #belajar #Indonesia #fyp",
        "caption": "belajar sambil nyetir, masak, atau olahraga? podcast jawabannya! 🎧📚\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 75,
        "judul": "pertanyaan seru buat quality time bareng doi malam ini!",
        "category": "tips",
        "like": 15900,
        "posting_ulang": 920,
        "share": 13700,
        "hashtags": "#romance #qualitytime #couple #tipspacaran #explorepage",
        "caption": "matiin Netflix dulu, cobain ini lebih seru! 🎲🌙\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 113,
        "judul": "perbedaan UI dan UX design yang sering tertukar!",
        "category": "technology",
        "like": 16400,
        "posting_ulang": 960,
        "share": 14100,
        "hashtags": "#technology #UIdesign #UXdesign #design #explorepage",
        "caption": "beda banget lho, ini penjelasan simpelnya! 🎨💡\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 147,
        "judul": "manfaat minum teh hijau setiap pagi yang terbukti ilmiah!",
        "category": "health",
        "like": 16500,
        "posting_ulang": 960,
        "share": 14100,
        "hashtags": "#health #greentea #tehijau #tipssehat #explorepage",
        "caption": "ganti kopi pagi dengan ini, rasain bedanya dalam seminggu! ☕🍵\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 85,
        "judul": "cara rekonsiliasi hubungan yang sempat renggang!",
        "category": "relationship",
        "like": 16700,
        "posting_ulang": 980,
        "share": 14200,
        "hashtags": "#relationship #reconciliation #friendship #tips #explorepage",
        "caption": "ada yang lagi cold war? mungkin ini waktunya berdamai 🤝✨\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 128,
        "judul": "kenapa critical thinking penting di era informasi sekarang!",
        "category": "education",
        "like": 16700,
        "posting_ulang": 980,
        "share": 14300,
        "hashtags": "#education #criticalthinking #mindset #awareness #fyp",
        "caption": "jangan telan informasi mentah-mentah, ajarkan ini ke diri sendiri! 🧠🔍\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 20,
        "judul": "shortcut keyboard yang wajib diketahui pengguna Windows!",
        "category": "technology",
        "like": 16300,
        "posting_ulang": 1050,
        "share": 14800,
        "hashtags": "#technology #windows #tips #productivity #fyp",
        "caption": "nomor 5 pasti banyak yang belum tahu! 🖥️⚡\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 158,
        "judul": "pengalaman KKN yang wajib kamu maksimalkan!",
        "category": "education",
        "like": 17200,
        "posting_ulang": 1010,
        "share": 14800,
        "hashtags": "#college #KKN #mahasiswa #pengalaman #fyp",
        "caption": "KKN bukan cuma kewajiban, ini kenangan yang ngga bisa dibeli! 🏕️🌾\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 56,
        "judul": "ide journaling harian yang bikin hidup lebih mindful!",
        "category": "lifestyle",
        "like": 17400,
        "posting_ulang": 980,
        "share": 15200,
        "hashtags": "#lifestyle #journaling #selfcare #mindfulness #fyp",
        "caption": "nulis bukan cuma buat penulis, ini buktinya! 📓🌿\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 31,
        "judul": "makanan yang bagus dikonsumsi saat stres berat!",
        "category": "health",
        "like": 17600,
        "posting_ulang": 1020,
        "share": 15300,
        "hashtags": "#health #stressrelief #makansehat #mentalhealth #fyp",
        "caption": "emotional eating boleh, asal pilih yang bener! 🍫🥜\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 142,
        "judul": "cara batch processing tugas biar selesai lebih cepat!",
        "category": "productivity",
        "like": 17800,
        "posting_ulang": 1050,
        "share": 15400,
        "hashtags": "#productivity #batching #timemanagement #efficiency #fyp",
        "caption": "kerja lebih sedikit, hasilnya lebih banyak? bisa! 🔄⚡\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 131,
        "judul": "cara belajar matematika dengan cara yang menyenangkan!",
        "category": "education",
        "like": 18100,
        "posting_ulang": 1060,
        "share": 15800,
        "hashtags": "#education #matematika #belajar #studytips #explorepage",
        "caption": "matematika itu seru kalau tau triknya! 🔢✨\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 94,
        "judul": "cara belajar dari orang yang lebih sukses dari kamu!",
        "category": "productivity",
        "like": 18200,
        "posting_ulang": 1080,
        "share": 15900,
        "hashtags": "#selfgrowth #mentor #learning #success #fyp",
        "caption": "jangan iri, jadikan mereka gurumu! 🧠🌟\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 169,
        "judul": "perbedaan reksa dana pasar uang vs reksa dana saham!",
        "category": "finance",
        "like": 18300,
        "posting_ulang": 1080,
        "share": 15900,
        "hashtags": "#finance #reksadana #investasi #tips #explorepage",
        "caption": "sebelum beli reksa dana, pahami dulu perbedaannya! 💼📈\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 68,
        "judul": "playlist spotify buat road trip bareng pasangan!",
        "category": "tips",
        "like": 18600,
        "posting_ulang": 1090,
        "share": 16200,
        "hashtags": "#romance #playlist #spotify #couple #fyp",
        "caption": "tinggal connect, play, dan nikmatin momennya 🎵🚗\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 153,
        "judul": "cara membangun rutinitas olahraga yang konsisten!",
        "category": "health",
        "like": 18700,
        "posting_ulang": 1100,
        "share": 16300,
        "hashtags": "#health #olahraga #consistency #routine #explorepage",
        "caption": "bukan soal intensitas, tapi konsistensi yang menang! 🏅💪\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 38,
        "judul": "cara bikin catatan kuliah yang enak dibaca ulang!",
        "category": "education",
        "like": 18900,
        "posting_ulang": 1100,
        "share": 16500,
        "hashtags": "#college #studytips #notetaking #mahasiswa #explorepage",
        "caption": "metode Cornell vs Mind Map, mana yang kamu pakai? 📓✏️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 12,
        "judul": "tips outfit aesthetic ke kampus buat cewek!",
        "category": "fashion",
        "like": 18900,
        "posting_ulang": 940,
        "share": 16700,
        "hashtags": "#fashion #ootd #campusstyle #outfitideas #explorepage",
        "caption": "mau ke kampus tapi tetep stylish? ini dia insponya! 👗✨\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 137,
        "judul": "cara pakai Google Calendar buat atur jadwal harian!",
        "category": "productivity",
        "like": 19300,
        "posting_ulang": 1140,
        "share": 17000,
        "hashtags": "#productivity #googlecalendar #timemanagement #tips #explorepage",
        "caption": "hidup teratur dimulai dari kalender yang teratur! 📅⚡\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 47,
        "judul": "perbedaan aset dan liabilitas yang wajib kamu tahu!",
        "category": "finance",
        "like": 19400,
        "posting_ulang": 1150,
        "share": 17200,
        "hashtags": "#finance #literasikeuangan #aset #tipskeuangan #fyp",
        "caption": "rich dad poor dad bilang ini, dan mereka bener! 📚💡\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 123,
        "judul": "outfit kerja yang stylish tanpa terlihat berlebihan!",
        "category": "fashion",
        "like": 19600,
        "posting_ulang": 1150,
        "share": 17200,
        "hashtags": "#fashion #workwear #officelook #ootd #explorepage",
        "caption": "profesional di kantor, tetap keren di luar kantor! 💼👔\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 108,
        "judul": "cara jaga privasi digital kamu dari ancaman hacker!",
        "category": "technology",
        "like": 19800,
        "posting_ulang": 1160,
        "share": 17400,
        "hashtags": "#technology #cybersecurity #privacy #tips #fyp",
        "caption": "data kamu berharga, jangan sampai dicuri! 🔐🛡️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 173,
        "judul": "kenapa kamu harus punya asuransi jiwa sejak muda!",
        "category": "finance",
        "like": 19800,
        "posting_ulang": 1170,
        "share": 17500,
        "hashtags": "#finance #asuransi #insurance #tipskeuangan #explorepage",
        "caption": "bukan soal takut mati, tapi soal melindungi orang tersayang! 🛡️❤️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 81,
        "judul": "cara minta maaf yang tulus dan benar-benar diterima!",
        "category": "relationship",
        "like": 21300,
        "posting_ulang": 1270,
        "share": 18900,
        "hashtags": "#relationship #apology #communication #tips #explorepage",
        "caption": "maaf bukan cuma kata, ini cara yang beneran works! 🙏🏻💙\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 97,
        "judul": "cara negosiasi harga yang sopan tapi efektif!",
        "category": "tips",
        "like": 21600,
        "posting_ulang": 1280,
        "share": 18900,
        "hashtags": "#tips #negosiasi #life #skill #fyp",
        "caption": "skill ini berguna seumur hidup, makanya wajib dipelajari! 🤝💬\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 150,
        "judul": "makanan yang bantu recovery setelah olahraga berat!",
        "category": "health",
        "like": 21400,
        "posting_ulang": 1270,
        "share": 18900,
        "hashtags": "#health #postworkout #recovery #nutrition #fyp",
        "caption": "makan yang bener setelah gym = otot tumbuh lebih optimal! 🥩🥑\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 133,
        "judul": "cara membuat mind map yang efektif untuk belajar!",
        "category": "education",
        "like": 21600,
        "posting_ulang": 1280,
        "share": 19100,
        "hashtags": "#education #mindmap #studytips #belajar #explorepage",
        "caption": "otak visual? mind map adalah sahabat terbaikmu! 🗺️🧠\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 39,
        "judul": "tips presentasi di depan dosen biar ngga grogi!",
        "category": "education",
        "like": 21700,
        "posting_ulang": 1290,
        "share": 19300,
        "hashtags": "#college #presentasi #publicspeaking #mahasiswa #fyp",
        "caption": "dosen killer pun bisa kamu taklukkan! 🎤💡\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 4,
        "judul": "ide topik buat deeptalk sama pasangan!",
        "category": "relationship",
        "like": 26800,
        "posting_ulang": 1552,
        "share": 19600,
        "hashtags": "#explorepage #exploremore #tips #deeptalk",
        "caption": "berani cobaa?\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 59,
        "judul": "cara bikin weekend reset yang benar-benar recharge!",
        "category": "lifestyle",
        "like": 22100,
        "posting_ulang": 1310,
        "share": 19600,
        "hashtags": "#lifestyle #weekendreset #selfcare #routine #fyp",
        "caption": "Senin siap tempur kalau Minggu diisi yang bener! 🌙💤\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 141,
        "judul": "tips remote working yang produktif dari rumah!",
        "category": "productivity",
        "like": 22100,
        "posting_ulang": 1310,
        "share": 19700,
        "hashtags": "#productivity #remotework #WFH #tips #explorepage",
        "caption": "kerja dari rumah bukan berarti santai, ini cara tetap on track! 🏠💻\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 27,
        "judul": "menu makan siang sehat dan murah buat anak kos!",
        "category": "health",
        "like": 22300,
        "posting_ulang": 1190,
        "share": 19800,
        "hashtags": "#health #makansehat #anakkos #mealprep #fyp",
        "caption": "sehat itu ngga harus mahal, beneran! 🥗💚\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 160,
        "judul": "cara menulis abstrak skripsi yang benar dan menarik!",
        "category": "education",
        "like": 22600,
        "posting_ulang": 1340,
        "share": 20000,
        "hashtags": "#college #skripsi #abstrak #tips #fyp",
        "caption": "abstrak yang bagus bikin penguji tertarik duluan! ✍️📑\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 16,
        "judul": "5 kebiasaan pagi yang bikin hari kamu lebih produktif",
        "category": "productivity",
        "like": 22700,
        "posting_ulang": 1340,
        "share": 20100,
        "hashtags": "#productivity #morningroutine #selfimprovement #tips #fyp",
        "caption": "mulai besok pagi, yuk cobain! ☀️💪\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 120,
        "judul": "rekomendasi brand lokal fashion Indonesia yang bagus!",
        "category": "fashion",
        "like": 22800,
        "posting_ulang": 1360,
        "share": 20100,
        "hashtags": "#fashion #brandlokal #Indonesia #ootd #fyp",
        "caption": "bangga pakai lokal, kualitasnya ngga kalah kok! 🇮🇩🌟\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 172,
        "judul": "cara bikin laporan keuangan personal bulanan yang simpel!",
        "category": "finance",
        "like": 22700,
        "posting_ulang": 1350,
        "share": 20200,
        "hashtags": "#finance #keuangan #budgeting #tracking #fyp",
        "caption": "ngga tau uangmu kemana? mulai tracking sekarang! 📓💰\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 110,
        "judul": "kenalan dengan Notion: cara setup untuk pemula!",
        "category": "technology",
        "like": 23100,
        "posting_ulang": 1380,
        "share": 20400,
        "hashtags": "#technology #Notion #productivity #tools #fyp",
        "caption": "dari chaos ke organized dalam satu app! 🗂️✨\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 72,
        "judul": "kalimat manis buat dikirim ke doi pas dia lagi kerja!",
        "category": "tips",
        "like": 23500,
        "posting_ulang": 1410,
        "share": 20700,
        "hashtags": "#romance #sweetmessage #couple #tipspacaran #fyp",
        "caption": "bikin dia senyum-senyum sendiri di kantor 😊💬\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 130,
        "judul": "perbedaan hard skill vs soft skill, mana yang lebih penting?",
        "category": "education",
        "like": 23400,
        "posting_ulang": 1390,
        "share": 20900,
        "hashtags": "#education #hardskill #softskill #career #fyp",
        "caption": "rekruter zaman sekarang ngga cuma lihat nilai! 💼🧠\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 50,
        "judul": "kenapa punya dana darurat itu penting banget?",
        "category": "finance",
        "like": 23800,
        "posting_ulang": 1420,
        "share": 21100,
        "hashtags": "#finance #daruratfund #tipskeuangan #literasikeuangan #explorepage",
        "caption": "bukan soal takut, tapi soal siap! 🛡️💰\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 32,
        "judul": "stretching pagi 5 menit yang bikin badan segar seharian!",
        "category": "health",
        "like": 24900,
        "posting_ulang": 1480,
        "share": 21700,
        "hashtags": "#health #stretching #morningroutine #olahraga #explorepage",
        "caption": "cobain dulu sebelum ngopi, dijamin beda rasanya! 🌅🧘\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 167,
        "judul": "apa itu inflasi dan kenapa mempengaruhi dompet kamu?",
        "category": "finance",
        "like": 24600,
        "posting_ulang": 1470,
        "share": 21800,
        "hashtags": "#finance #inflasi #literasikeuangan #ekonomi #explorepage",
        "caption": "harga naik terus bukan kebetulan, ini penjelasannya! 💹🧾\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 104,
        "judul": "tips public speaking buat introvert!",
        "category": "tips",
        "like": 25700,
        "posting_ulang": 1540,
        "share": 22300,
        "hashtags": "#tips #publicspeaking #introvert #confidence #explorepage",
        "caption": "introvert pun bisa jadi pembicara yang keren! 🎤🌟\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 125,
        "judul": "cara bikin capsule wardrobe dengan budget minim!",
        "category": "fashion",
        "like": 25900,
        "posting_ulang": 1560,
        "share": 22700,
        "hashtags": "#fashion #capsulewardrobe #minimalist #ootd #explorepage",
        "caption": "lebih sedikit pilihan, lebih mudah berpakaian! ✂️👗\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 162,
        "judul": "cara networking yang efektif sejak masih mahasiswa!",
        "category": "education",
        "like": 25100,
        "posting_ulang": 1500,
        "share": 22700,
        "hashtags": "#college #networking #career #mahasiswa #fyp",
        "caption": "koneksi yang kamu bangun sekarang = peluang 5 tahun ke depan! 🤝💼\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 170,
        "judul": "cara hitung kebutuhan dana pensiun dari sekarang!",
        "category": "finance",
        "like": 26200,
        "posting_ulang": 1570,
        "share": 23000,
        "hashtags": "#finance #pensiun #retirement #longtermsaving #fyp",
        "caption": "pensiun sejahtera dimulai dari keputusan kecil hari ini! 👴🏻💵\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 63,
        "judul": "kebiasaan malam yang bikin kamu lebih bahagia!",
        "category": "lifestyle",
        "like": 26300,
        "posting_ulang": 1570,
        "share": 23100,
        "hashtags": "#lifestyle #nightroutine #selfcare #happiness #fyp",
        "caption": "tidur dengan tenang dimulai dari kebiasaan ini 🌙🫶🏻\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 93,
        "judul": "cara konsisten dengan tujuan tanpa mudah menyerah!",
        "category": "productivity",
        "like": 26400,
        "posting_ulang": 1590,
        "share": 23100,
        "hashtags": "#selfgrowth #consistency #goals #discipline #explorepage",
        "caption": "motivasi itu naik turun, makanya butuh sistem! ⚙️🎯\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 140,
        "judul": "cara prioritas tugas dengan Eisenhower Matrix!",
        "category": "productivity",
        "like": 26800,
        "posting_ulang": 1620,
        "share": 23500,
        "hashtags": "#productivity #Eisenhower #prioritas #timemanagement #fyp",
        "caption": "mana yang urgent, mana yang penting? ini cara bedainnya! 📊🎯\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 48,
        "judul": "tips hemat belanja bulanan tanpa rasa tersiksa!",
        "category": "finance",
        "like": 26700,
        "posting_ulang": 1600,
        "share": 23900,
        "hashtags": "#finance #hemat #saving #lifehack #explorepage",
        "caption": "hidup hemat bukan berarti pelit, ini bedanya! 🛒✂️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 118,
        "judul": "tips belanja thrift yang dapat barang berkualitas!",
        "category": "fashion",
        "like": 27400,
        "posting_ulang": 1710,
        "share": 24000,
        "hashtags": "#fashion #thrifting #secondhand #sustainable #fyp",
        "caption": "fashion murah tapi ngga murahan, thrift is the way! 🛍️♻️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 35,
        "judul": "cara belajar efektif H-1 ujian tanpa begadang!",
        "category": "education",
        "like": 27300,
        "posting_ulang": 1630,
        "share": 24100,
        "hashtags": "#college #studytips #ujian #mahasiswa #fyp",
        "caption": "belajar sistem kebut semalam? ini triknya biar tetap masuk! 📚⚡\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 107,
        "judul": "ekstensi Chrome yang bikin browsing 10x lebih efisien!",
        "category": "technology",
        "like": 27600,
        "posting_ulang": 1740,
        "share": 24300,
        "hashtags": "#technology #chrome #extension #productivity #explorepage",
        "caption": "browser kamu masih polos tanpa ini? rugi banget! 🌐🔧\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 2,
        "judul": "ide pose foto lebaran!",
        "category": "lifestyle",
        "like": 33200,
        "posting_ulang": 1571,
        "share": 24500,
        "hashtags": "#explorepage #exploremore #tips #poseideas #pose",
        "caption": "save duluu biar nanti pas lebaran ngga mati gaya 🤭😋\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 146,
        "judul": "cara menjaga kesehatan mata bagi yang sering menatap layar!",
        "category": "health",
        "like": 27900,
        "posting_ulang": 1780,
        "share": 24600,
        "hashtags": "#health #matasehat #eyecare #tips #fyp",
        "caption": "rule 20-20-20 ini wajib kamu terapkan mulai sekarang! 👁️💻\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 70,
        "judul": "cara LDR tetap harmonis tanpa drama!",
        "category": "tips",
        "like": 27800,
        "posting_ulang": 1840,
        "share": 24900,
        "hashtags": "#romance #LDR #tipspacaran #couple #fyp",
        "caption": "jarak bukan halangan kalau caranya bener 💑📱\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 156,
        "judul": "cara cari dosen pembimbing skripsi yang cocok!",
        "category": "education",
        "like": 28400,
        "posting_ulang": 1870,
        "share": 25100,
        "hashtags": "#college #skripsi #mahasiswa #tips #fyp",
        "caption": "pilih dospem itu seperti pilih pasangan, penting banget! 👨‍🏫🤝\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 58,
        "judul": "rekomendasi cafe aesthetic buat nugas di Jakarta!",
        "category": "lifestyle",
        "like": 28700,
        "posting_ulang": 1730,
        "share": 25400,
        "hashtags": "#lifestyle #cafe #Jakarta #workfromcafe #explorepage",
        "caption": "WiFi kenceng + kopi enak = produktivitas maximal ☕💻\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 87,
        "judul": "buku self-improvement yang wajib dibaca usia 20-an!",
        "category": "productivity",
        "like": 28900,
        "posting_ulang": 1920,
        "share": 25600,
        "hashtags": "#selfgrowth #bookrecommendation #reading #tips #explorepage",
        "caption": "beli kopi boleh, tapi beli buku ini dulu! ☕📚\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 100,
        "judul": "tips jualan online yang laris di marketplace!",
        "category": "tips",
        "like": 29300,
        "posting_ulang": 1870,
        "share": 26100,
        "hashtags": "#tips #jualanOnline #marketplace #bisnis #explorepage",
        "caption": "ribuan seller, tapi yang ini beda strateginya! 🛍️📦\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 24,
        "judul": "gerakan olahraga 10 menit di rumah tanpa alat!",
        "category": "health",
        "like": 29600,
        "posting_ulang": 1740,
        "share": 26300,
        "hashtags": "#health #homeworkout #olahraga #fitnessmotivation #explorepage",
        "caption": "ngga ada alasan lagi buat males gerak! 💪🏠\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 83,
        "judul": "hal yang tidak boleh kamu tolerir dalam pertemanan!",
        "category": "relationship",
        "like": 29600,
        "posting_ulang": 1890,
        "share": 26400,
        "hashtags": "#relationship #friendship #toxicfriend #boundaries #explorepage",
        "caption": "sayang sama teman tapi juga harus sayang sama diri sendiri 💛\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 19,
        "judul": "cara jawab pertanyaan interview kerja yang tricky!",
        "category": "productivity",
        "like": 29100,
        "posting_ulang": 1890,
        "share": 26500,
        "hashtags": "#tips #interview #career #selfgrowth #explorepage",
        "caption": "screenshot dulu sebelum interview besok! 💼✅\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 132,
        "judul": "manfaat belajar coding meski bukan anak IT!",
        "category": "education",
        "like": 29700,
        "posting_ulang": 1930,
        "share": 26500,
        "hashtags": "#education #coding #technology #career #fyp",
        "caption": "di era digital, coding bukan cuma buat programmer! 💡👨‍💻\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 154,
        "judul": "suplemen yang benar-benar worth it untuk dibeli!",
        "category": "health",
        "like": 30100,
        "posting_ulang": 1980,
        "share": 27400,
        "hashtags": "#health #suplemen #supplement #tipssehat #fyp",
        "caption": "jangan buang uang untuk yang ngga perlu, ini yang penting! 💊✅\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 95,
        "judul": "kenapa self-talk positif itu bukan omong kosong!",
        "category": "productivity",
        "like": 30900,
        "posting_ulang": 2030,
        "share": 27600,
        "hashtags": "#selfgrowth #selftalk #mindset #mentalhealth #explorepage",
        "caption": "otak kamu percaya apa yang sering kamu ucapkan ke diri sendiri 🧠💬\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 163,
        "judul": "cara mengelola stres saat musim UTS dan UAS!",
        "category": "education",
        "like": 31400,
        "posting_ulang": 2060,
        "share": 28100,
        "hashtags": "#college #UTS #UAS #stressmanagement #explorepage",
        "caption": "ujian itu bisa dilewati, asal persiapannya bener! 💪📖\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 114,
        "judul": "cara pakai Canva buat desain konten yang aesthetic!",
        "category": "technology",
        "like": 31500,
        "posting_ulang": 2080,
        "share": 28200,
        "hashtags": "#technology #Canva #design #konten #fyp",
        "caption": "ngga perlu jago desain, Canva udah urus semuanya! 🎨📱\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 121,
        "judul": "cara berdandan natural untuk sehari-hari (no makeup look)!",
        "category": "fashion",
        "like": 31700,
        "posting_ulang": 2100,
        "share": 28300,
        "hashtags": "#fashion #makeup #nomakeupmakeup #beauty #explorepage",
        "caption": "keliatan seger dan fresh tanpa effort berlebihan! 💄✨\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 52,
        "judul": "cara mulai investasi emas dari modal 10 ribu!",
        "category": "finance",
        "like": 31100,
        "posting_ulang": 1970,
        "share": 28500,
        "hashtags": "#finance #investasiemas #gold #tipskeuangan #fyp",
        "caption": "ga perlu nunggu kaya dulu buat mulai investasi! 🥇📲\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 61,
        "judul": "manfaat digital detox seminggu yang jarang disadari!",
        "category": "lifestyle",
        "like": 31800,
        "posting_ulang": 2040,
        "share": 28500,
        "hashtags": "#lifestyle #digitaldetox #mentalhealth #offline #fyp",
        "caption": "coba deh lepas HP 1 hari, rasain bedanya! 📵🌿\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 168,
        "judul": "cara lunasi utang dengan metode debt snowball!",
        "category": "finance",
        "like": 31900,
        "posting_ulang": 2110,
        "share": 28600,
        "hashtags": "#finance #utang #debtfree #tipskeuangan #fyp",
        "caption": "bebas utang itu mungkin kalau punya strategi yang tepat! 🏔️💰\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 42,
        "judul": "cara survive semester padat tanpa burnout!",
        "category": "education",
        "like": 31800,
        "posting_ulang": 2050,
        "share": 28700,
        "hashtags": "#college #mahasiswa #burnout #selfcare #explorepage",
        "caption": "IP bagus tapi kesehatan juga dijaga ya bestie 🌿📚\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 136,
        "judul": "cara kerja deep focus tanpa gangguan selama 2 jam!",
        "category": "productivity",
        "like": 32400,
        "posting_ulang": 2160,
        "share": 29100,
        "hashtags": "#productivity #deepwork #focus #tips #fyp",
        "caption": "2 jam fokus = 6 jam kerja biasa, ini ilmunya! ⏱️🧠\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 90,
        "judul": "tanda kamu sudah berkembang tanpa kamu sadari!",
        "category": "productivity",
        "like": 33600,
        "posting_ulang": 2210,
        "share": 30100,
        "hashtags": "#selfgrowth #awareness #progress #motivation #fyp",
        "caption": "kadang kita terlalu fokus kurang, lupa betapa jauhnya kita sudah melangkah 🌱💛\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 7,
        "judul": "ide birthday wishes biar ngga bosenin",
        "category": "lifestyle",
        "like": 31300,
        "posting_ulang": 2149,
        "share": 30200,
        "hashtags": "#explorepage #exploremore #tips #birthdaygirl",
        "caption": "klo km ulang tahun, pengennya diucapin yang kayak gimanaaa?\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 67,
        "judul": "cara nyatain perasaan tanpa takut ditolak!",
        "category": "tips",
        "like": 33900,
        "posting_ulang": 2270,
        "share": 30400,
        "hashtags": "#romance #confession #tipspacaran #crush #explorepage",
        "caption": "yang masih memendam, ini tanda kamu harus baca ini 👀💌\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 96,
        "judul": "tips foto produk UMKM yang terlihat profesional!",
        "category": "tips",
        "like": 33800,
        "posting_ulang": 2270,
        "share": 30500,
        "hashtags": "#tips #UMKM #fotoproduk #bisnis #explorepage",
        "caption": "pakai HP biasa juga bisa, ini caranya! 📸💡\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 36,
        "judul": "rekomendasi platform magang terbaik buat mahasiswa!",
        "category": "education",
        "like": 33500,
        "posting_ulang": 2180,
        "share": 30900,
        "hashtags": "#college #magang #internship #career #explorepage",
        "caption": "CV kosong pengalaman? nih solusinya! 💼🔥\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 148,
        "judul": "cara deteksi gejala anemia yang sering diabaikan!",
        "category": "health",
        "like": 34200,
        "posting_ulang": 2280,
        "share": 30900,
        "hashtags": "#health #anemia #awareness #tipssehat #fyp",
        "caption": "sering pusing dan lemas? jangan anggap remeh! 🩸⚠️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 135,
        "judul": "cara efektif menghafal materi dalam waktu singkat!",
        "category": "education",
        "like": 34600,
        "posting_ulang": 2310,
        "share": 31200,
        "hashtags": "#education #memorizationtips #studyhacks #belajar #explorepage",
        "caption": "teknik spaced repetition ini terbukti secara ilmiah! 🧪📖\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 80,
        "judul": "perbedaan cinta yang sehat vs cinta yang obsesif!",
        "category": "relationship",
        "like": 34700,
        "posting_ulang": 2340,
        "share": 31300,
        "hashtags": "#relationship #healthylove #awareness #tipspacaran #fyp",
        "caption": "cinta itu harusnya bikin kamu tumbuh, bukan terkurung 💛🌱\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 18,
        "judul": "cara mengelola keuangan bulanan untuk anak kos!",
        "category": "education",
        "like": 35400,
        "posting_ulang": 2100,
        "share": 31600,
        "hashtags": "#education #financialtips #anakkos #saving #fyp",
        "caption": "gaji/uang saku habis di tengah bulan? ini solusinya! 💸📊\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 86,
        "judul": "cara keluar dari comfort zone tanpa overwhelmed!",
        "category": "productivity",
        "like": 35200,
        "posting_ulang": 2360,
        "share": 31800,
        "hashtags": "#selfgrowth #comfortzone #motivation #mindset #fyp",
        "caption": "growth selalu ada di luar zona nyamanmu! 🚀🌟\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 144,
        "judul": "cara automasi tugas berulang dengan tools gratis!",
        "category": "productivity",
        "like": 35100,
        "posting_ulang": 2370,
        "share": 31800,
        "hashtags": "#productivity #automation #Zapier #tools #fyp",
        "caption": "biarkan teknologi kerja, kamu fokus yang penting! 🤖⚙️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 49,
        "judul": "metode budgeting 50/30/20 untuk pemula!",
        "category": "finance",
        "like": 35600,
        "posting_ulang": 2340,
        "share": 32100,
        "hashtags": "#finance #budgeting #tipskeuangan #saving #fyp",
        "caption": "kalau gajian tinggal ngilang, coba metode ini dulu! 💸📊\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 159,
        "judul": "cara cari kerja sambil kuliah tanpa nilai jeblok!",
        "category": "education",
        "like": 35700,
        "posting_ulang": 2400,
        "share": 32300,
        "hashtags": "#college #parttime #mahasiswa #career #explorepage",
        "caption": "uang jajan dari kerja sendiri itu rasanya beda! 💰📚\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 71,
        "judul": "ide hadiah anniversary yang meaningful dan personal!",
        "category": "tips",
        "like": 36400,
        "posting_ulang": 2490,
        "share": 33100,
        "hashtags": "#romance #anniversary #giftideas #couple #explorepage",
        "caption": "bukan soal harganya, tapi maknanya yang bikin nangis 🎁🥹\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 29,
        "judul": "cara kelola anxiety dengan teknik 5-4-3-2-1!",
        "category": "health",
        "like": 36900,
        "posting_ulang": 2540,
        "share": 33200,
        "hashtags": "#mentalhealth #anxiety #selfhelp #health #fyp",
        "caption": "simpan ini, siapa tahu kamu atau temanmu butuh nanti 🫶🏻\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 116,
        "judul": "cara mix and match baju dengan 5 item basic doang!",
        "category": "fashion",
        "like": 36900,
        "posting_ulang": 2480,
        "share": 33400,
        "hashtags": "#fashion #mixandmatch #ootd #minimalist #fyp",
        "caption": "lemari penuh tapi ngaku ngga punya baju? ini solusinya! 👗✨\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 155,
        "judul": "tanda tubuh kamu butuh istirahat yang sering diabaikan!",
        "category": "health",
        "like": 36800,
        "posting_ulang": 2490,
        "share": 33400,
        "hashtags": "#health #rest #recovery #tipssehat #explorepage",
        "caption": "dengerin sinyal tubuhmu, itu bahasa yang dia pakai buat bicara! 🛌💛\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 166,
        "judul": "cara mulai trading saham untuk pemula tanpa rugi besar!",
        "category": "finance",
        "like": 37400,
        "posting_ulang": 2530,
        "share": 33900,
        "hashtags": "#finance #saham #trading #investasi #fyp",
        "caption": "trading bukan judi kalau kamu paham risikonya! 📈📊\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 101,
        "judul": "cara minta kenaikan gaji ke atasan tanpa awkward!",
        "category": "tips",
        "like": 37600,
        "posting_ulang": 2490,
        "share": 34000,
        "hashtags": "#tips #salary #career #negotiation #fyp",
        "caption": "kamu berhak dibayar sesuai nilaimu! ini script-nya 💼💰\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 84,
        "judul": "tanda kamu punya trust issues dan cara mengatasinya!",
        "category": "relationship",
        "like": 37800,
        "posting_ulang": 2540,
        "share": 34100,
        "hashtags": "#relationship #trustissues #healing #selfgrowth #fyp",
        "caption": "luka lama sering jadi penghalang hubungan baru 💔🌱\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 22,
        "judul": "7 tips tidur berkualitas yang jarang orang tahu!",
        "category": "health",
        "like": 38400,
        "posting_ulang": 2310,
        "share": 34700,
        "hashtags": "#health #sleeproutine #tipssehat #selfcare #explorepage",
        "caption": "tidur 8 jam tapi masih ngantuk? mungkin ini masalahnya! 😴✨\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 76,
        "judul": "cara komunikasi yang baik saat lagi ada konflik!",
        "category": "relationship",
        "like": 38100,
        "posting_ulang": 2560,
        "share": 34700,
        "hashtags": "#relationship #communication #tipspacaran #couple #fyp",
        "caption": "beda pendapat itu wajar, yang penting cara ngomongnya! 🗣️💬\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 127,
        "judul": "cara belajar bahasa Inggris sendiri sampai fasih!",
        "category": "education",
        "like": 38200,
        "posting_ulang": 2590,
        "share": 34800,
        "hashtags": "#education #english #belajarbahasa #tips #explorepage",
        "caption": "les mahal bukan satu-satunya jalan, ini alternatifnya! 🌍🗣️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 109,
        "judul": "rekomendasi laptop terbaik untuk mahasiswa 2025!",
        "category": "technology",
        "like": 38700,
        "posting_ulang": 2610,
        "share": 35200,
        "hashtags": "#technology #laptop #review #mahasiswa #explorepage",
        "caption": "jangan beli sebelum baca ini dulu! 💻📊\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 164,
        "judul": "hal yang harus disiapkan sebelum wisuda dan setelahnya!",
        "category": "education",
        "like": 38900,
        "posting_ulang": 2670,
        "share": 35500,
        "hashtags": "#college #wisuda #graduation #mahasiswa #fyp",
        "caption": "selamat ya calon sarjana! ini checklist yang wajib kamu siapkan 🎓🎉\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 57,
        "judul": "aesthetic room decor dengan budget di bawah 200 ribu!",
        "category": "lifestyle",
        "like": 39200,
        "posting_ulang": 2610,
        "share": 35800,
        "hashtags": "#lifestyle #roomdecor #aesthetic #homedecor #explorepage",
        "caption": "kamar aesthetic ngga harus mahal, percaya deh! 🛋️✨\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 91,
        "judul": "cara menerima kegagalan dan bangkit lebih kuat!",
        "category": "productivity",
        "like": 39400,
        "posting_ulang": 2680,
        "share": 35900,
        "hashtags": "#selfgrowth #failure #resilience #motivation #explorepage",
        "caption": "gagal bukan akhir, tapi bagian dari proses 🔥💪\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 151,
        "judul": "cara kelola emosi saat lagi PMS dengan efektif!",
        "category": "health",
        "like": 39600,
        "posting_ulang": 2730,
        "share": 36200,
        "hashtags": "#health #PMS #womenshealth #selfcare #explorepage",
        "caption": "buat para cewek, ini bukan lebay tapi sains! 🌸💊\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 34,
        "judul": "tips mulai skripsi dari nol biar ngga overwhelmed!",
        "category": "education",
        "like": 39800,
        "posting_ulang": 2760,
        "share": 36400,
        "hashtags": "#college #skripsi #studytips #mahasiswa #explorepage",
        "caption": "buat yang baru mulai bab 1, semangat ya! 📝🎓\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 122,
        "judul": "tren fashion Korea yang cocok buat tubuh Asia!",
        "category": "fashion",
        "like": 41300,
        "posting_ulang": 2870,
        "share": 37900,
        "hashtags": "#fashion #kfashion #Korea #ootd #fyp",
        "caption": "gaya oppa dan unnie tapi versi kita sendiri! 🇰🇷👗\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 74,
        "judul": "love language kamu apa? ini penjelasan lengkapnya!",
        "category": "tips",
        "like": 41600,
        "posting_ulang": 2830,
        "share": 38100,
        "hashtags": "#romance #lovelanguage #relationship #couple #fyp",
        "caption": "pahami love language pasangan = hubungan jauh lebih happy 💞\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 89,
        "judul": "cara membangun kepercayaan diri dari nol!",
        "category": "productivity",
        "like": 41800,
        "posting_ulang": 2890,
        "share": 38200,
        "hashtags": "#selfgrowth #confidence #selfesteem #motivation #explorepage",
        "caption": "percaya diri itu skill yang bisa dilatih, bukan bawaan lahir! 💪✨\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 161,
        "judul": "tips lolos seleksi student exchange ke luar negeri!",
        "category": "education",
        "like": 41800,
        "posting_ulang": 2940,
        "share": 38300,
        "hashtags": "#college #studentexchange #abroad #beasiswa #explorepage",
        "caption": "kuliah di luar negeri bukan mimpi, ini langkah nyatanya! 🌏✈️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 46,
        "judul": "investasi pemula: pilih reksa dana, saham, atau emas?",
        "category": "finance",
        "like": 42100,
        "posting_ulang": 2890,
        "share": 38600,
        "hashtags": "#finance #investasi #reksadana #saham #explorepage",
        "caption": "jangan tunda lagi, uangmu butuh kerja juga! 📈💼\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 103,
        "judul": "cara cepat belajar skill baru dalam 30 hari!",
        "category": "tips",
        "like": 42100,
        "posting_ulang": 2930,
        "share": 38700,
        "hashtags": "#tips #learning #skill #selfimprovement #fyp",
        "caption": "30 hari bisa jadi titik balik hidupmu! 📅🚀\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 15,
        "judul": "red flags dalam hubungan yang sering diabaikan",
        "category": "relationship",
        "like": 41200,
        "posting_ulang": 2780,
        "share": 38900,
        "hashtags": "#relationship #redflag #mentalhealth #selfcare #explorepage",
        "caption": "please jangan diabaikan ya bestie 🚩💔\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 115,
        "judul": "tren teknologi 2025 yang bakal mengubah cara kerja kita!",
        "category": "technology",
        "like": 42600,
        "posting_ulang": 2950,
        "share": 39000,
        "hashtags": "#technology #trend2025 #AI #futureofwork #explorepage",
        "caption": "siap-siap atau ketinggalan, pilihannya cuma dua! 🌐🔮\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 64,
        "judul": "aplikasi wajib punya buat atur hidup lebih terorganisir!",
        "category": "lifestyle",
        "like": 43500,
        "posting_ulang": 2980,
        "share": 39700,
        "hashtags": "#lifestyle #apps #productivity #organized #explorepage",
        "caption": "download semua, rasain bedanya dalam seminggu! 📱⚡\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 82,
        "judul": "cara dukung teman yang lagi mental breakdown!",
        "category": "relationship",
        "like": 43200,
        "posting_ulang": 3010,
        "share": 39800,
        "hashtags": "#relationship #mentalhealth #support #friendship #fyp",
        "caption": "jadi teman yang hadir bukan cuma saat senang! 🫂💜\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 26,
        "judul": "cara menjaga kesehatan mental di tengah kesibukan!",
        "category": "health",
        "like": 43700,
        "posting_ulang": 2980,
        "share": 40500,
        "hashtags": "#mentalhealth #selfcare #health #mindfulness #explorepage",
        "caption": "ingatkan dirimu: istirahat itu bukan kelemahan 🧠🌿\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 152,
        "judul": "bahaya overthinking bagi kesehatan fisik yang jarang dibahas!",
        "category": "health",
        "like": 44300,
        "posting_ulang": 3090,
        "share": 40800,
        "hashtags": "#health #overthinking #mentalhealth #anxiety #fyp",
        "caption": "pikiran negatif itu literally bikin sakit, ini buktinya! 🧠⚠️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 41,
        "judul": "tools gratis yang wajib dipakai setiap mahasiswa!",
        "category": "education",
        "like": 44600,
        "posting_ulang": 3040,
        "share": 41200,
        "hashtags": "#college #tools #studytips #technology #fyp",
        "caption": "Notion, Zotero, Grammarly... udah pakai semua belum? 🛠️💻\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 66,
        "judul": "ide date murah tapi berkesan buat pasangan!",
        "category": "tips",
        "like": 44700,
        "posting_ulang": 3120,
        "share": 41300,
        "hashtags": "#romance #dateideas #couple #tipspacaran #fyp",
        "caption": "romantis itu bukan soal mahal, ini buktinya 🌹🕯️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 126,
        "judul": "platform kursus online gratis terbaik selain YouTube!",
        "category": "education",
        "like": 44900,
        "posting_ulang": 3190,
        "share": 41500,
        "hashtags": "#education #onlinecourse #belajar #freecourse #fyp",
        "caption": "ilmu gratis itu ada di mana-mana, tinggal mau cari atau ngga! 📱📚\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 33,
        "judul": "perbedaan lelah fisik vs lelah mental, kamu yang mana?",
        "category": "health",
        "like": 45100,
        "posting_ulang": 3200,
        "share": 41800,
        "hashtags": "#mentalhealth #health #selfawareness #burnout #fyp",
        "caption": "penting banget buat bisa bedain ini! jangan salah tangani 🙏🏻\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 157,
        "judul": "cara dapat IPK tinggi tanpa harus jadi kutu buku!",
        "category": "education",
        "like": 46300,
        "posting_ulang": 3320,
        "share": 42700,
        "hashtags": "#college #IPK #studytips #mahasiswa #explorepage",
        "caption": "smart work bukan hard work, ini bedanya! 📊🎓\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 99,
        "judul": "cara bikin CV yang langsung dilirik HRD!",
        "category": "tips",
        "like": 46200,
        "posting_ulang": 3340,
        "share": 42800,
        "hashtags": "#tips #CV #career #job #fyp",
        "caption": "6 detik pertama HRD lihat CV kamu, pastikan berkesan! 📄✅\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 111,
        "judul": "belajar coding dari nol: roadmap lengkap 2025!",
        "category": "technology",
        "like": 46800,
        "posting_ulang": 3380,
        "share": 43100,
        "hashtags": "#technology #coding #programming #belajarcoding #explorepage",
        "caption": "ngga ada kata terlambat buat belajar coding! 👨‍💻🚀\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 79,
        "judul": "cara set boundaries yang tegas tanpa menyakiti orang lain!",
        "category": "relationship",
        "like": 46900,
        "posting_ulang": 3280,
        "share": 43200,
        "hashtags": "#relationship #boundaries #selfrespect #mentalhealth #explorepage",
        "caption": "punya batasan bukan berarti kamu jahat! 🛑🌿\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 88,
        "judul": "cara berhenti procrastinate mulai dari sekarang!",
        "category": "productivity",
        "like": 47300,
        "posting_ulang": 3450,
        "share": 43900,
        "hashtags": "#selfgrowth #procrastination #productivity #tips #fyp",
        "caption": "kalau nunggu mood, ngga akan pernah mulai! ini solusinya ⚡\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 117,
        "judul": "outfit kondangan yang kekinian tapi tetap sopan!",
        "category": "fashion",
        "like": 48100,
        "posting_ulang": 3560,
        "share": 44700,
        "hashtags": "#fashion #kondangan #ootd #weddingguest #explorepage",
        "caption": "jangan sampai jadi pusat perhatian yang salah ya! 😂👒\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 45,
        "judul": "cara nabung 1 juta pertama kamu di usia 20-an!",
        "category": "finance",
        "like": 48300,
        "posting_ulang": 3560,
        "share": 44900,
        "hashtags": "#finance #nabung #saving #tipskeuangan #fyp",
        "caption": "mulai dari yang kecil, konsisten dulu yang penting! 💰🎯\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 145,
        "judul": "tanda kamu sedang burnout dan cara mengatasinya!",
        "category": "productivity",
        "like": 48700,
        "posting_ulang": 3560,
        "share": 44900,
        "hashtags": "#productivity #burnout #mentalhealth #selfcare #explorepage",
        "caption": "produktif itu penting, tapi istirahat lebih penting! 🔋🌿\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 73,
        "judul": "cara move on yang sehat dan ngga menyiksa diri!",
        "category": "tips",
        "like": 49800,
        "posting_ulang": 3760,
        "share": 45200,
        "hashtags": "#romance #moveon #healing #selfcare #explorepage",
        "caption": "kamu berhak bahagia setelah ini semua 🌱💛\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 65,
        "judul": "cara bikin vision board yang beneran works!",
        "category": "lifestyle",
        "like": 52100,
        "posting_ulang": 3840,
        "share": 47600,
        "hashtags": "#lifestyle #visionboard #manifestasi #goals #fyp",
        "caption": "bukan sekadar tempel foto, ini cara yang bener! 🎯🖼️\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 23,
        "judul": "makanan yang WAJIB dihindari kalo mau kulit glowing!",
        "category": "health",
        "like": 51200,
        "posting_ulang": 3870,
        "share": 47900,
        "hashtags": "#health #skincare #glowingskin #makansehat #fyp",
        "caption": "nomor 3 pasti masih sering kamu makan 😬🫣\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 92,
        "judul": "kebiasaan toxic yang menghambat pertumbuhanmu!",
        "category": "productivity",
        "like": 52700,
        "posting_ulang": 3920,
        "share": 48400,
        "hashtags": "#selfgrowth #toxichabits #awareness #tips #fyp",
        "caption": "nomor 4 paling banyak yang ngga sadar melakukannya 😬🚩\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 43,
        "judul": "pertanyaan yang sering keluar saat sidang skripsi!",
        "category": "education",
        "like": 53700,
        "posting_ulang": 4120,
        "share": 49300,
        "hashtags": "#college #skripsi #sidang #mahasiswa #fyp",
        "caption": "print, tempel di meja, hafalin! kamu pasti bisa lulus 💪🎓\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 149,
        "judul": "olahraga terbaik buat yang mau turun berat badan!",
        "category": "health",
        "like": 52800,
        "posting_ulang": 3980,
        "share": 49300,
        "hashtags": "#health #weightloss #olahraga #fitness #explorepage",
        "caption": "ngga perlu gym mahal, ini yang benar-benar efektif! 🏃‍♀️🔥\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 165,
        "judul": "rekomendasi side hustle terbaik buat mahasiswa 2025!",
        "category": "education",
        "like": 53200,
        "posting_ulang": 4010,
        "share": 49600,
        "hashtags": "#college #sidehustle #mahasiswa #income #explorepage",
        "caption": "bukan cuma nunggu beasiswa, bisa cari income sendiri! 💡💸\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 106,
        "judul": "cara pakai ChatGPT buat bantu kerja sehari-hari!",
        "category": "technology",
        "like": 54300,
        "posting_ulang": 4120,
        "share": 50700,
        "hashtags": "#technology #chatgpt #AI #productivity #fyp",
        "caption": "yang belum pakai AI buat kerja, ketinggalan banget! 🤖⚡\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 77,
        "judul": "tanda hubungan kamu sudah tidak sehat!",
        "category": "relationship",
        "like": 55400,
        "posting_ulang": 4190,
        "share": 51000,
        "hashtags": "#relationship #toxicrelationship #redflag #awareness #explorepage",
        "caption": "kalau ada 3 dari ini, please consider talking to someone 🚩💔\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 175,
        "judul": "kesalahan keuangan paling umum di usia 20-an!",
        "category": "finance",
        "like": 55900,
        "posting_ulang": 4280,
        "share": 51600,
        "hashtags": "#finance #tipskeuangan #literasikeuangan #usia20an #explorepage",
        "caption": "masih bisa diperbaiki sekarang sebelum terlambat! 🔁💡\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 11,
        "judul": "aplikasi AI gratis yang wajib kamu coba di 2025!",
        "category": "technology",
        "like": 47800,
        "posting_ulang": 3210,
        "share": 52300,
        "hashtags": "#technology #AI #apprecommendation #fyp #explorepage",
        "caption": "save dulu, nyesel kalo kelewatan! 🤖✨\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 51,
        "judul": "jebakan finansial yang sering dialami anak muda!",
        "category": "finance",
        "like": 57200,
        "posting_ulang": 4380,
        "share": 52800,
        "hashtags": "#finance #tipskeuangan #literasikeuangan #fyp #explorepage",
        "caption": "FOMO, paylater, lifestyle inflation... kamu kena yang mana? 👀💳\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 98,
        "judul": "tips lolos seleksi beasiswa LPDP untuk pemula!",
        "category": "tips",
        "like": 58400,
        "posting_ulang": 4560,
        "share": 54100,
        "hashtags": "#tips #LPDP #beasiswa #education #explorepage",
        "caption": "dari essay sampai wawancara, semua ada di sini! 🎓🔥\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 174,
        "judul": "cara passive income dari modal kecil yang realistis!",
        "category": "finance",
        "like": 61700,
        "posting_ulang": 4820,
        "share": 57300,
        "hashtags": "#finance #passiveincome #investasi #finansialbebas #fyp",
        "caption": "uang bekerja saat kamu tidur, ini bukan mimpi! 💤💸\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 69,
        "judul": "tanda-tanda dia diam-diam suka sama kamu!",
        "category": "tips",
        "like": 61300,
        "posting_ulang": 4570,
        "share": 57800,
        "hashtags": "#romance #crush #tanda #tipspacaran #explorepage",
        "caption": "scroll sambil mikirin seseorang? itu pertanda! 🫣💗\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 55,
        "judul": "mindset keuangan orang kaya vs orang miskin!",
        "category": "finance",
        "like": 62400,
        "posting_ulang": 4890,
        "share": 58100,
        "hashtags": "#finance #mindset #literasikeuangan #motivasi #fyp",
        "caption": "bukan soal jumlah uangnya, tapi cara pikirnya! 🧠💎\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
    {
        "id": 105,
        "judul": "cara bikin konten viral di TikTok dari nol!",
        "category": "tips",
        "like": 63900,
        "posting_ulang": 5010,
        "share": 59200,
        "hashtags": "#tips #TikTok #konten #viral #fyp",
        "caption": "0 follower sampai FYP, ini perjalanannya! 🎬🔥\n— cover photo : pinterest\n🥟 request thread? dm aja!\n🍙 tag temen/sahabat/keluarga/pacar kamu!",
    },
]